### ISSUE TITLE
Support for golden seed and sacred tears..etc?

### ISSUE THREAD

**Issue by MehdiMamas** [elden-ring-progression-tracker/elden-ring-progression-tracker.github.io#11]
I stumbled across your fascinating tool because I was looking for a tool that can help me find which golden seeds that I didn't collect, after a couple hours in the game of course I don't remember which golden seeds I took and which I didn't haha.

Let me know if there will be support for that, I would love to try it!

**Comment by Zidodelakarai** [comment]
Hi! It's not planned to track Golden Seeds because they are not permanent items, they reset in NG+, same for Scadutree fragments etc...
