### ISSUE TITLE
Tracker reset itself 

### ISSUE THREAD

**Issue by AniviasWaifuExe** [elden-ring-progression-tracker/elden-ring-progression-tracker.github.io#7]
Hi! First of all, love your work, it helped me a lot in progressing the game when I was stuck. But today (20.06) after the dlc update the main save tracker completely cleared out itself, shows only 1% completed when yesterday it was nearly 30%. It also cleared the items I have already collected. Here are screenshots if you need them. 
Thanks!
![Untitled](https://github.com/elden-ring-progression-tracker/elden-ring-progression-tracker.github.io/assets/91792892/14c8f0b8-2355-4207-a37c-3f5271721219)

![Untitled](https://github.com/elden-ring-progression-tracker/elden-ring-progression-tracker.github.io/assets/91792892/2b150224-c829-4b10-8bb7-9e3a9170409e)

**Comment by Zidodelakarai** [comment]
Thanks for your report! Alas with the DLC's release, the save files have probably changed a lot. It might take some time to fix this issue but I will fix it, one day...

**Comment by Zidodelakarai** [comment]
It was easier than I thought, the problem is fixed!

**Comment by kingboyman** [comment]
this is still an issue i cannot access it

**Comment by Zidodelakarai** [comment]
@kingboyman Can you send me your save file so I can see the problem please?

**Comment by kingboyman** [comment]
i do not know how to send the save, but i can send the same thing i saw as the person before me

> @kingboyman Can you send me your save file so I can see the problem please?

**Comment by AniviasWaifuExe** [comment]
omg it's working! thank you so so so much <333
![image](https://github.com/elden-ring-progression-tracker/elden-ring-progression-tracker.github.io/assets/91792892/5b1b8478-91db-48a7-bc1c-b58702376b02)

**Comment by kingboyman** [comment]
Hey is it because i dont have the dlc yet? its only showing up as 2% and that is cause of my collectibles, it says i haven't collected any item from any area

**Comment by Zidodelakarai** [comment]
@kingboyman I tested my fix with both a dlc save file and a vanilla save file, it worked with both. Do you use mods or any other things that can alter your save file?

**Comment by kingboyman** [comment]
I have been using a boss rush style save file that has the world mainly looted except for the bosses and quests. It was working find when i used the save file thw first time and for a good week or so after. I havent used any mods since i got it but i know the cheat engine was used to help creating it, nothing game breaking just like adding some items and junk

**Comment by Zidodelakarai** [comment]
Can you send me your file so I can search the problem please? (Usually located in C:/Users/yourName/AppData/Roaming/EldenRing/aNumber/ER0000.sl2)

**Comment by Zidodelakarai** [comment]
It's fixed!

**Comment by kingboyman** [comment]
Wait what happened what was the issue? Also thank you so much

**Comment by Zidodelakarai** [comment]
For a reason that I don't understand, the pattern which I search in the save file was slightly different in your save file than mine.
