### ISSUE TITLE
Dagger causing to show incomplete

### ISSUE THREAD

**Issue by glametrix** [elden-ring-progression-tracker/elden-ring-progression-tracker.github.io#8]
I have 10 daggers I have collected everywhere throughout, following your guide here.

It still shows I don't have the standard dagger. It's the only thing keeping me from showing 100%.

Obviously, it's a bug, but it's a super frustrating bug, lol. My OCD is going crazy over here!

It says I am missing four items in Limgrave, for example. All four items are the same dagger. 

I even went and farmed the dagger in each area and bought the one from the round table. Nothing will fix it.

**Comment by Zidodelakarai** [comment]
Sorry for that bug, it's now fixed (you may have to clean your cache to make it work)!
Congratulations for the 100% 🥳
