### ISSUE TITLE
Add support for Shadow of the Erdtree DLC items

### ISSUE THREAD

**Issue by hriewe** [elden-ring-progression-tracker/elden-ring-progression-tracker.github.io#9]
With the recent release of the Shadow of the Erdtree DLC expansion, hundreds of new items were added to the game. Added support to check the progression on these new items would be required for the tool to be feature complete. QOL feature would be the ability to separate these items from the main games items.

**Comment by Zidodelakarai** [comment]
I will work on it after finishing the DLC, it will take some time...

**Comment by Zidodelakarai** [comment]
I forgot to close this issue, DLC was implemented few weeks ago.
